---
title: "Week 09 Statistical Machine Learning in Bioinformatics: Tree based methods Book lab 8.3"
output: 
  html_document:
    code_folding: show
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r}
library(ISLR2)
library(tree)

attach(Carseats)

```




# 8.3.1 Fitting Classification Trees
```{r}
High=factor(ifelse(Sales<=8,"No","Yes"))
```

```{r}
Carseats=data.frame(Carseats,High)
```


```{r}
tree.carseats=tree(High~.-Sales,Carseats)
```

```{r}
summary(tree.carseats)
```


```{r}
set.seed(2)
train=sample(1:nrow(Carseats),200)
Carseats.test=Carseats[-train,]
High.test=High[-train]
tree.carseats=tree(High~.-Sales,Carseats,subset=train)
tree.pred=predict(tree.carseats,Carseats.test,type="class")
table(tree.pred,High.test)

```

```{r}
set.seed(7)
cv.carseats=cv.tree(tree.carseats,FUN=prune.misclass)
names(cv.carseats)
```

```{r}
par(mfrow=c(1,2))
plot(cv.carseats$size,cv.carseats$dev,type="b")
plot(cv.carseats$k,cv.carseats$dev,type="b")

```

```{r}
prune.carseats=prune.misclass(tree.carseats,best=9)
plot(prune.carseats)
text(prune.carseats,pretty=0)
```

```{r}
tree.pred=predict(prune.carseats,Carseats.test,type="class")
table(tree.pred,High.test)
```


# 8.3.2 Fitting Regression Trees

```{r}
set.seed(1)
train=sample(1:nrow(Boston),nrow(Boston)/2)
tree.boston=tree(medv~.,Boston,subset=train)
summary(tree.boston)
```

```{r}
plot(tree.boston)
text(tree.boston,pretty=0)
```

```{r}
cv.boston=cv.tree(tree.boston)
plot(cv.boston$size,cv.boston$dev,type="b")
```

```{r}
prune.boston=prune.tree(tree.boston,best=5)
plot(prune.boston)
text(prune.boston,pretty=0)
```
```{r}
yhat=predict(prune.boston,newdata=Boston[-train,])
boston.test=Boston[-train,"medv"]
plot(yhat,boston.test)
abline(0,1)
mean((yhat-boston.test)^2)
```

# 8.3.3 Bagging and Random Forests
```{r}
library(randomForest)

```
```{r}
set.seed(1)
bag.boston=randomForest(medv~.,data=Boston,subset=train,mtry=12,importance=TRUE)
```
```{r}
bag.boston
```
```{r}
yhat.bag=predict(bag.boston,newdata=Boston[-train,])
plot(yhat.bag,boston.test)
abline(0,1)
mean((yhat.bag-boston.test)^2)
```
### why this no worky?
```{r}
bag.boston=randomForest(medv~.,data=Boston,mtry=12,ntree=25)
yhat.bag=predict(bag.boston,newdata=Boston[-train,])
mean((yhat.bag-boston.test)^2)
```

```{r}
set.seed(1)
rf.boston=randomForest(medv~.,data=Boston,subset=train,mtry=6,importance=TRUE)
yhat.rf=predict(rf.boston,newdata=Boston[-train,])
mean((yhat.rf-boston.test)^2)
```

```{r}
importance(rf.boston)
```
```{r}
varImpPlot(rf.boston)
```

# 8.3.4 Boosting
```{r}
library(gbm)

```
```{r}
set.seed(1)
boost.boston=gbm(medv~.,data=Boston[train,],distribution="gaussian",n.trees=5000,interaction.depth=4)
```

```{r}
summary(boost.boston)
```

```{r}
plot(boost.boston,i="rm")
plot(boost.boston,i="lstat")
```

```{r}
yhat.boost=predict(boost.boston,newdata=Boston[-train,],n.trees=5000)
mean((yhat.boost-boston.test)^2)
```

```{r}
boost.boston=gbm(medv~.,data=Boston[train,],distribution="gaussian",n.trees=5000,interaction.depth=4,shrinkage=0.2)
yhat.boost=predict(boost.boston,newdata=Boston[-train,],n.trees=5000)
mean((yhat.boost-boston.test)^2)
```

# 8.3.5 Bayesian Additive Regression Trees
```{r}
library(BART)
```

```{r}
x = Boston[,1:12]
y = Boston[,"medv"]
xtrain = x[train,]
ytrain = y[train]
xtest = x[-train,]
ytest = y[-train]
set.seed(1)
bartfit = gbart(xtrain, ytrain, x.test=xtest)
```
```{r}
yhat.bart = bartfit$yhat.test.mean
mean((yhat.bart-ytest)^2)
```
```{r}
ord = order(bartfit$varcount.mean,decreasing=T)
bartfit$varcount.mean[ord]
```